### Get Token from auth server
POST http://localhost:9000/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic messaging-client:secret

grant_type=client_credentials&scope=message.read%20message.write

### GetBeer for spring mvc

GET http://localhost:8080/api/v1/beer
Authorization: Bearer eyJraWQiOiJlZWJlNWNhNi1mM2I5LTQ5YjYtOTZkNC0xMWEzY2VkMjNiMWMiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTcyMzc4ODMwOSwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJleHAiOjE3MjM3ODg2MDksImlhdCI6MTcyMzc4ODMwOSwianRpIjoiOTdjZjYyYWYtNGE4YS00ZTk5LWI1MjgtY2YwNTk1ZGFmYTc2In0.LytIlj2KQd9JkbXjoA2ZJezhStv9zxQEdSX5_5osaOFe6H2dAeYkDesp8qVdAUj9tz2OuvkUrh8vlrayClRJpt6hJSvhFQ2fJbLcXUplfXMS0pC4O0tmicEKLJFa9u_67AnjZEkMPTwwrD-_9JcLXHNuTgXaJex26A996s3E2AKi0DVj3FO1Eqs3Vx5F21JanKhFh95xLHYCh_O_7qCrF0My4qhuS8fgh0Yf3NG-uK2PdAk_rAeQVFt1f7pNyV-oUnxLWx3sM9XiYRrzweq7QzV7RfHo95byswNOR-A2xbOQY3dw1e_c2iQMHMKvhLmkW5ivRSIfj6kehgWQpQav3Q

### 
GET http://localhost:8080/api/v2/beer
Authorization: Bearer eyJraWQiOiJlZWJlNWNhNi1mM2I5LTQ5YjYtOTZkNC0xMWEzY2VkMjNiMWMiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTcyMzc4ODMwOSwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJleHAiOjE3MjM3ODg2MDksImlhdCI6MTcyMzc4ODMwOSwianRpIjoiOTdjZjYyYWYtNGE4YS00ZTk5LWI1MjgtY2YwNTk1ZGFmYTc2In0.LytIlj2KQd9JkbXjoA2ZJezhStv9zxQEdSX5_5osaOFe6H2dAeYkDesp8qVdAUj9tz2OuvkUrh8vlrayClRJpt6hJSvhFQ2fJbLcXUplfXMS0pC4O0tmicEKLJFa9u_67AnjZEkMPTwwrD-_9JcLXHNuTgXaJex26A996s3E2AKi0DVj3FO1Eqs3Vx5F21JanKhFh95xLHYCh_O_7qCrF0My4qhuS8fgh0Yf3NG-uK2PdAk_rAeQVFt1f7pNyV-oUnxLWx3sM9XiYRrzweq7QzV7RfHo95byswNOR-A2xbOQY3dw1e_c2iQMHMKvhLmkW5ivRSIfj6kehgWQpQav3Q

### 
GET http://localhost:8080/api/beer
Authorization: Bearer eyJraWQiOiJlZWJlNWNhNi1mM2I5LTQ5YjYtOTZkNC0xMWEzY2VkMjNiMWMiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTcyMzc4ODMwOSwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJleHAiOjE3MjM3ODg2MDksImlhdCI6MTcyMzc4ODMwOSwianRpIjoiOTdjZjYyYWYtNGE4YS00ZTk5LWI1MjgtY2YwNTk1ZGFmYTc2In0.LytIlj2KQd9JkbXjoA2ZJezhStv9zxQEdSX5_5osaOFe6H2dAeYkDesp8qVdAUj9tz2OuvkUrh8vlrayClRJpt6hJSvhFQ2fJbLcXUplfXMS0pC4O0tmicEKLJFa9u_67AnjZEkMPTwwrD-_9JcLXHNuTgXaJex26A996s3E2AKi0DVj3FO1Eqs3Vx5F21JanKhFh95xLHYCh_O_7qCrF0My4qhuS8fgh0Yf3NG-uK2PdAk_rAeQVFt1f7pNyV-oUnxLWx3sM9XiYRrzweq7QzV7RfHo95byswNOR-A2xbOQY3dw1e_c2iQMHMKvhLmkW5ivRSIfj6kehgWQpQav3Q
