### Get Token from auth server
POST http://localhost:9000/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic messaging-client:secret

grant_type=client_credentials&scope=message.read%20message.write

### GetBeer for spring mvc

GET http://localhost:8080/api/v1/beer
Authorization: Bearer eyJraWQiOiJlZWJlNWNhNi1mM2I5LTQ5YjYtOTZkNC0xMWEzY2VkMjNiMWMiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTcyMzc5MDEwNCwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJleHAiOjE3MjM3OTA0MDQsImlhdCI6MTcyMzc5MDEwNCwianRpIjoiZWFiNjM4ZTMtMGM3ZC00MzJmLWI1ZTUtNWEwNTI1NjQ0ODcwIn0.JUAyyEkknd06YJZf3PBlO_WD95Sntj4VRtKEOWtCaH2tEvM9Wq5iGSF26mEgUhLX2Ga7tBSj-OiS1tUWIWvijHrMVa0FcNs1OxPDLll3WmDuLAlQ5neKX_gAZzkRfygoy6d6vRUxtQiGUGmKibehI5kYyNSH2OSJcN4OvWNN1d8q_PgRbo-O4-gYgDSx9NmokmTFZRC5ByvSi-HNTDJKd3f7CGfkDGlG_FJSPc1i7pkD4TZV7cFr6R2AQh-jJeknK65qsGSmuMKmjhEGw7dOjqxYMDUwPlePvHhUTLtH04s66AZSjgsCwlfQTtqwHBIltprDWjNDVRO4v_CgYzdGiw

### 
GET http://localhost:8080/api/v2/beer
Authorization: Bearer eyJraWQiOiJlZWJlNWNhNi1mM2I5LTQ5YjYtOTZkNC0xMWEzY2VkMjNiMWMiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTcyMzc5MDEwNCwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJleHAiOjE3MjM3OTA0MDQsImlhdCI6MTcyMzc5MDEwNCwianRpIjoiZWFiNjM4ZTMtMGM3ZC00MzJmLWI1ZTUtNWEwNTI1NjQ0ODcwIn0.JUAyyEkknd06YJZf3PBlO_WD95Sntj4VRtKEOWtCaH2tEvM9Wq5iGSF26mEgUhLX2Ga7tBSj-OiS1tUWIWvijHrMVa0FcNs1OxPDLll3WmDuLAlQ5neKX_gAZzkRfygoy6d6vRUxtQiGUGmKibehI5kYyNSH2OSJcN4OvWNN1d8q_PgRbo-O4-gYgDSx9NmokmTFZRC5ByvSi-HNTDJKd3f7CGfkDGlG_FJSPc1i7pkD4TZV7cFr6R2AQh-jJeknK65qsGSmuMKmjhEGw7dOjqxYMDUwPlePvHhUTLtH04s66AZSjgsCwlfQTtqwHBIltprDWjNDVRO4v_CgYzdGiw

### 
GET http://localhost:8080/api/beer
Authorization: Bearer eyJraWQiOiJlZWJlNWNhNi1mM2I5LTQ5YjYtOTZkNC0xMWEzY2VkMjNiMWMiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTcyMzc5MDEwNCwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJleHAiOjE3MjM3OTA0MDQsImlhdCI6MTcyMzc5MDEwNCwianRpIjoiZWFiNjM4ZTMtMGM3ZC00MzJmLWI1ZTUtNWEwNTI1NjQ0ODcwIn0.JUAyyEkknd06YJZf3PBlO_WD95Sntj4VRtKEOWtCaH2tEvM9Wq5iGSF26mEgUhLX2Ga7tBSj-OiS1tUWIWvijHrMVa0FcNs1OxPDLll3WmDuLAlQ5neKX_gAZzkRfygoy6d6vRUxtQiGUGmKibehI5kYyNSH2OSJcN4OvWNN1d8q_PgRbo-O4-gYgDSx9NmokmTFZRC5ByvSi-HNTDJKd3f7CGfkDGlG_FJSPc1i7pkD4TZV7cFr6R2AQh-jJeknK65qsGSmuMKmjhEGw7dOjqxYMDUwPlePvHhUTLtH04s66AZSjgsCwlfQTtqwHBIltprDWjNDVRO4v_CgYzdGiw
