GET http://localhost:8080/api/v1/beer

###
GET http://localhost:8080/api/v1/beer/0e5be93b-dd1a-4c2d-8817-b3ee35143eeb

###
POST http://localhost:8080/api/v1/beer
content-type: application/json

 {
    "version": 2,
    "beerName": "Stella",
    "beerStyle": "PALE_ALE",
    "upc": "upc",
    "quantityOnHand": 15,
    "price": 13.0
  }

###
PUT http://localhost:8080/api/v1/beer/e52516b8-8881-4d32-ac2a-1e526a4171d2
content-type: application/json

 {
    "beerName": "Stella-Updated",
    "beerStyle": "PALE_ALE",
    "upc": "upc",
    "quantityOnHand": 15,
    "price": 13.0
  }

### 

GET http://localhost:8080/api/v1/customer

###
GET http://localhost:8080/api/v1/customer/58ea5d98-c18e-41c9-8ce5-b3cd4f5add01

### 
POST http://localhost:8080/api/v1/customer
content-type: application/json

 {
    "customerName": "Roman",
    "version": 1
  }
