### Beer

GET http://localhost:8080/api/v1/beer?pageSize=1&pageNumber=25
Authorization: Bearer eyJraWQiOiJiMjEwODc5NC05YjM2LTQ4MjQtYjBjZS1jMTczZDMxZGI4ZmIiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTcyMjgyNDQ4OCwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJleHAiOjE3MjI4MjQ3ODgsImlhdCI6MTcyMjgyNDQ4OCwianRpIjoiZjlkNDU0ZWEtN2UwYy00MmFjLTg1NDgtNjYzNzExOTBhNzkyIn0.V2PZezamogK43yeWUlnzWh2Sh1VXNBEx2vaoKws6GKy90ZomkZbdNTOVABgxEZuLp6l59zuLfIDbAH9hQfNZYeJD34DPhRnQ-SzPx19obF24eLB5WrMPyZdLgACI-qK3OwnV4Qgz92OI0kLvcStxzXZhVhRmEw9EH_hR-Wm8qnRnPFU5fzsfXJO1KgYffqxPUCqkXTnewto4s2ClKy0E8h_wy3J7iIq7y5ydWzKrpbQOc1yvHaGpFPvCty6284q70rFuE5XA4eXUo1VxPei3FHisW894O241h0ih5SOJzMIwbi62J4ttUjTxMCN35MZqAYZWjs2lYqkMEl8NpUhrWQ

### Beer

GET http://localhost:8080/api/v1/beer?beerStyle=ALE
Authorization: Bearer eyJraWQiOiJiMjEwODc5NC05YjM2LTQ4MjQtYjBjZS1jMTczZDMxZGI4ZmIiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTcyMjgyNDQ4OCwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJleHAiOjE3MjI4MjQ3ODgsImlhdCI6MTcyMjgyNDQ4OCwianRpIjoiZjlkNDU0ZWEtN2UwYy00MmFjLTg1NDgtNjYzNzExOTBhNzkyIn0.V2PZezamogK43yeWUlnzWh2Sh1VXNBEx2vaoKws6GKy90ZomkZbdNTOVABgxEZuLp6l59zuLfIDbAH9hQfNZYeJD34DPhRnQ-SzPx19obF24eLB5WrMPyZdLgACI-qK3OwnV4Qgz92OI0kLvcStxzXZhVhRmEw9EH_hR-Wm8qnRnPFU5fzsfXJO1KgYffqxPUCqkXTnewto4s2ClKy0E8h_wy3J7iIq7y5ydWzKrpbQOc1yvHaGpFPvCty6284q70rFuE5XA4eXUo1VxPei3FHisW894O241h0ih5SOJzMIwbi62J4ttUjTxMCN35MZqAYZWjs2lYqkMEl8NpUhrWQ



### 
GET http://localhost:8080/api/v1/beer/2a291c61-d709-419f-8a2b-a0257f5149ad
Authorization: Bearer eyJraWQiOiJiMjEwODc5NC05YjM2LTQ4MjQtYjBjZS1jMTczZDMxZGI4ZmIiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTcyMjgyNDQ4OCwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJleHAiOjE3MjI4MjQ3ODgsImlhdCI6MTcyMjgyNDQ4OCwianRpIjoiZjlkNDU0ZWEtN2UwYy00MmFjLTg1NDgtNjYzNzExOTBhNzkyIn0.V2PZezamogK43yeWUlnzWh2Sh1VXNBEx2vaoKws6GKy90ZomkZbdNTOVABgxEZuLp6l59zuLfIDbAH9hQfNZYeJD34DPhRnQ-SzPx19obF24eLB5WrMPyZdLgACI-qK3OwnV4Qgz92OI0kLvcStxzXZhVhRmEw9EH_hR-Wm8qnRnPFU5fzsfXJO1KgYffqxPUCqkXTnewto4s2ClKy0E8h_wy3J7iIq7y5ydWzKrpbQOc1yvHaGpFPvCty6284q70rFuE5XA4eXUo1VxPei3FHisW894O241h0ih5SOJzMIwbi62J4ttUjTxMCN35MZqAYZWjs2lYqkMEl8NpUhrWQ

###
POST http://localhost:8080/api/v1/beer
Authorization: Bearer eyJraWQiOiJiMjEwODc5NC05YjM2LTQ4MjQtYjBjZS1jMTczZDMxZGI4ZmIiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTcyMjgyNDQ4OCwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJleHAiOjE3MjI4MjQ3ODgsImlhdCI6MTcyMjgyNDQ4OCwianRpIjoiZjlkNDU0ZWEtN2UwYy00MmFjLTg1NDgtNjYzNzExOTBhNzkyIn0.V2PZezamogK43yeWUlnzWh2Sh1VXNBEx2vaoKws6GKy90ZomkZbdNTOVABgxEZuLp6l59zuLfIDbAH9hQfNZYeJD34DPhRnQ-SzPx19obF24eLB5WrMPyZdLgACI-qK3OwnV4Qgz92OI0kLvcStxzXZhVhRmEw9EH_hR-Wm8qnRnPFU5fzsfXJO1KgYffqxPUCqkXTnewto4s2ClKy0E8h_wy3J7iIq7y5ydWzKrpbQOc1yvHaGpFPvCty6284q70rFuE5XA4eXUo1VxPei3FHisW894O241h0ih5SOJzMIwbi62J4ttUjTxMCN35MZqAYZWjs2lYqkMEl8NpUhrWQ
Content-Type: application/json

{
  "beerName": "1492",
  "beerStyle": "ALE",
  "upc": "369",
  "quantityOnHand": 369,
  "price": 10.00
}

###

DELETE http://localhost:8080/api/v1/beer/fbb8e132-210b-424f-b22f-004d18c13841
Authorization: Bearer eyJraWQiOiJiMjEwODc5NC05YjM2LTQ4MjQtYjBjZS1jMTczZDMxZGI4ZmIiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTcyMjgyNDQ4OCwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJleHAiOjE3MjI4MjQ3ODgsImlhdCI6MTcyMjgyNDQ4OCwianRpIjoiZjlkNDU0ZWEtN2UwYy00MmFjLTg1NDgtNjYzNzExOTBhNzkyIn0.V2PZezamogK43yeWUlnzWh2Sh1VXNBEx2vaoKws6GKy90ZomkZbdNTOVABgxEZuLp6l59zuLfIDbAH9hQfNZYeJD34DPhRnQ-SzPx19obF24eLB5WrMPyZdLgACI-qK3OwnV4Qgz92OI0kLvcStxzXZhVhRmEw9EH_hR-Wm8qnRnPFU5fzsfXJO1KgYffqxPUCqkXTnewto4s2ClKy0E8h_wy3J7iIq7y5ydWzKrpbQOc1yvHaGpFPvCty6284q70rFuE5XA4eXUo1VxPei3FHisW894O241h0ih5SOJzMIwbi62J4ttUjTxMCN35MZqAYZWjs2lYqkMEl8NpUhrWQ


###
PUT http://localhost:8080/api/v1/beer/e52516b8-8881-4d32-ac2a-1e526a4171d2
content-type: application/json
Authorization: Bearer eyJraWQiOiJiMjEwODc5NC05YjM2LTQ4MjQtYjBjZS1jMTczZDMxZGI4ZmIiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTcyMjgyNDQ4OCwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJleHAiOjE3MjI4MjQ3ODgsImlhdCI6MTcyMjgyNDQ4OCwianRpIjoiZjlkNDU0ZWEtN2UwYy00MmFjLTg1NDgtNjYzNzExOTBhNzkyIn0.V2PZezamogK43yeWUlnzWh2Sh1VXNBEx2vaoKws6GKy90ZomkZbdNTOVABgxEZuLp6l59zuLfIDbAH9hQfNZYeJD34DPhRnQ-SzPx19obF24eLB5WrMPyZdLgACI-qK3OwnV4Qgz92OI0kLvcStxzXZhVhRmEw9EH_hR-Wm8qnRnPFU5fzsfXJO1KgYffqxPUCqkXTnewto4s2ClKy0E8h_wy3J7iIq7y5ydWzKrpbQOc1yvHaGpFPvCty6284q70rFuE5XA4eXUo1VxPei3FHisW894O241h0ih5SOJzMIwbi62J4ttUjTxMCN35MZqAYZWjs2lYqkMEl8NpUhrWQ

 {
    "beerName": "Stella-Updated",
    "beerStyle": "PALE_ALE",
    "upc": "upc",
    "quantityOnHand": 15,
    "price": 13.0
  }

### CUSTOMER

GET http://localhost:8080/api/v1/customer

###
GET http://localhost:8080/api/v1/customer/58ea5d98-c18e-41c9-8ce5-b3cd4f5add01

### 
POST http://localhost:8080/api/v1/customer
content-type: application/json

 {
    "customerName": "Roman",
    "version": 1
  }


### 
PUT http://localhost:8080/api/v1/customer/3d33c159-59e6-498a-938c-50c30d99e5d1
content-type: application/json

 {
    "customerName": "Roman"
 }

###
DELETE http://localhost:8080/api/v1/customer/f537170f-65eb-47a7-ad63-fc8992d09969