### Beer

GET http://localhost:8080/api/v1/beer?pageSize=1&pageNumber=25
Authorization: Basic user:password

### Beer

GET http://localhost:8080/api/v1/beer?beerStyle=ALE
Authorization: Basic user:password



### 
GET http://localhost:8080/api/v1/beer/fbb8e132-210b-424f-b22f-004d18c13841
Authorization: Basic user:password

###
POST http://localhost:8080/api/v1/beer
Authorization: Basic user:password
Content-Type: application/json

{
  "beerName": "1492",
  "beerStyle": "ALE",
  "upc": "369",
  "quantityOnHand": 369,
  "price": 10.00,
}

###

DELETE http://localhost:8080/api/v1/beer/fbb8e132-210b-424f-b22f-004d18c13841
Authorization: Basic user:283b2bf2-5b1e-4236-abe2-b5bb9f27b659


###
PUT http://localhost:8080/api/v1/beer/e52516b8-8881-4d32-ac2a-1e526a4171d2
content-type: application/json

 {
    "beerName": "Stella-Updated",
    "beerStyle": "PALE_ALE",
    "upc": "upc",
    "quantityOnHand": 15,
    "price": 13.0
  }

### CUSTOMER

GET http://localhost:8080/api/v1/customer

###
GET http://localhost:8080/api/v1/customer/58ea5d98-c18e-41c9-8ce5-b3cd4f5add01

### 
POST http://localhost:8080/api/v1/customer
content-type: application/json

 {
    "customerName": "Roman",
    "version": 1
  }


### 
PUT http://localhost:8080/api/v1/customer/3d33c159-59e6-498a-938c-50c30d99e5d1
content-type: application/json

 {
    "customerName": "Roman"
 }

###
DELETE http://localhost:8080/api/v1/customer/f537170f-65eb-47a7-ad63-fc8992d09969