spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: spring-rest-mvc
          uri: http://rest-mvc:8081
          predicates:
            - Path=/api/v1/**
        - id: spring-webflux
          uri: http://reactive:8082
          predicates:
            - Path=/api/v2/**            
        - id: spring-webflux-fn
          uri: http://reactive-mongo:8083
          predicates:
            - Path=/api/**         
        - id: auth-server
          uri: http://auth-server:9000
          predicates:
            - Path=/oauth2/**         