version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dev-network
    depends_on:
      db:
        condition: service_healthy
    command: sleep infinity

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: prateek
      MYSQL_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin  ping  -h  localhost --silent"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - 3306:3306  # Expose port 5432
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge