version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - ${HOME}/.ssh:/root/.ssh:cached     # needed for ssh auth for github, or other servers
    command: sleep infinity