### GET BEERS

GET http://localhost:8080/api/beer

### GET BEERS BY ID

GET http://localhost:8080/api/beer/66bacef39a965d41443ab1a

### CREATE BEER

POST http://localhost:8080/api/beer
Content-Type: application/json

{
  "beerName": "Beer 4",
  "beerStyle": "PALE_ALE",
  "upc": "upc",
  "quantityOnHand": 10,
  "price": 10
}

### UPDATE BEER

PUT http://localhost:8080/api/beer/66bad24270ebec2471c78ac6
Content-Type: application/json

{
  "beerName": "Beer 5",
  "beerStyle": "PALE_ALE",
  "upc": "upc",
  "quantityOnHand": 10,
  "price": 10
}