### Actuator Endpoint

GET http://localhost:8083/actuator/health

### Kubernetes liveness Endpoint
GET http://localhost:8083/actuator/health/liveness

### Kubernetes readiness Endpoints
GET http://localhost:8083/actuator/health/readiness

### Get Token from auth server 
POST http://localhost:9000/oauth2/token 
Content-Type: application/x-www-form-urlencoded 
Authorization: Basic messaging-client:secret

grant_type=client_credentials&scope=message.read%20message.write

### GET BEERS

GET http://localhost:8080/api/beer
Authorization: Bearer eyJraWQiOiJlM2I0OWYyYy1kYjg4LTQxMzEtOGQyNC03MDhjMmE1MWRlZGYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTcyMzY5NTQ1NCwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJleHAiOjE3MjM2OTU3NTQsImlhdCI6MTcyMzY5NTQ1NCwianRpIjoiMmM2NDhjNDctNzEzZS00MmJhLTg5ZDAtZDY3NzRmYjgzYWZhIn0.UjE2of73f6xN_X59OWDlZym4lL_OH1iKAhYh3mHM4_QOva-RTtaIubm8p_WT6ETIQYtHt5Ll4V1_UK41bmnJnBFRFKMOH_1P8TAYHngjG1SgljXe22cDrU74iP6KPcZKv_EVMgHpye_cWD4D-tUn_3NhBAD6OsPSARHSTYAinL2xSeMVKFatnS7scxMrF2UJjLt1BRORqYJwu8KCgTNHuzGLn853dOMdVK_t-QYig9IpLXiTaIGLPn__HrWvU-BMijufDrKb0k0egX3rtiRcs4jmQn6pcrkshwcSGpYREzLAN8XcbWRdkX0lIBuS2smVkXCMIdCd50Eoqa7304yrzw

### GET BEERS BY ID

GET http://localhost:8080/api/beer/66bd81b9a797b40fda7be08c
Authorization: Bearer eyJraWQiOiJlM2I0OWYyYy1kYjg4LTQxMzEtOGQyNC03MDhjMmE1MWRlZGYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTcyMzY5NTQ1NCwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJleHAiOjE3MjM2OTU3NTQsImlhdCI6MTcyMzY5NTQ1NCwianRpIjoiMmM2NDhjNDctNzEzZS00MmJhLTg5ZDAtZDY3NzRmYjgzYWZhIn0.UjE2of73f6xN_X59OWDlZym4lL_OH1iKAhYh3mHM4_QOva-RTtaIubm8p_WT6ETIQYtHt5Ll4V1_UK41bmnJnBFRFKMOH_1P8TAYHngjG1SgljXe22cDrU74iP6KPcZKv_EVMgHpye_cWD4D-tUn_3NhBAD6OsPSARHSTYAinL2xSeMVKFatnS7scxMrF2UJjLt1BRORqYJwu8KCgTNHuzGLn853dOMdVK_t-QYig9IpLXiTaIGLPn__HrWvU-BMijufDrKb0k0egX3rtiRcs4jmQn6pcrkshwcSGpYREzLAN8XcbWRdkX0lIBuS2smVkXCMIdCd50Eoqa7304yrzw


### CREATE BEER

POST http://localhost:8080/api/beer
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJlM2I0OWYyYy1kYjg4LTQxMzEtOGQyNC03MDhjMmE1MWRlZGYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTcyMzY5NTQ1NCwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJleHAiOjE3MjM2OTU3NTQsImlhdCI6MTcyMzY5NTQ1NCwianRpIjoiMmM2NDhjNDctNzEzZS00MmJhLTg5ZDAtZDY3NzRmYjgzYWZhIn0.UjE2of73f6xN_X59OWDlZym4lL_OH1iKAhYh3mHM4_QOva-RTtaIubm8p_WT6ETIQYtHt5Ll4V1_UK41bmnJnBFRFKMOH_1P8TAYHngjG1SgljXe22cDrU74iP6KPcZKv_EVMgHpye_cWD4D-tUn_3NhBAD6OsPSARHSTYAinL2xSeMVKFatnS7scxMrF2UJjLt1BRORqYJwu8KCgTNHuzGLn853dOMdVK_t-QYig9IpLXiTaIGLPn__HrWvU-BMijufDrKb0k0egX3rtiRcs4jmQn6pcrkshwcSGpYREzLAN8XcbWRdkX0lIBuS2smVkXCMIdCd50Eoqa7304yrzw

{
  "beerName": "Beer 4",
  "beerStyle": "PALE_ALE",
  "upc": "upc",
  "quantityOnHand": 10,
  "price": 10
}

### UPDATE BEER

PUT http://localhost:8080/api/beer/66bd81b9a797b40fda7be08c
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJlM2I0OWYyYy1kYjg4LTQxMzEtOGQyNC03MDhjMmE1MWRlZGYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTcyMzY5NTQ1NCwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJleHAiOjE3MjM2OTU3NTQsImlhdCI6MTcyMzY5NTQ1NCwianRpIjoiMmM2NDhjNDctNzEzZS00MmJhLTg5ZDAtZDY3NzRmYjgzYWZhIn0.UjE2of73f6xN_X59OWDlZym4lL_OH1iKAhYh3mHM4_QOva-RTtaIubm8p_WT6ETIQYtHt5Ll4V1_UK41bmnJnBFRFKMOH_1P8TAYHngjG1SgljXe22cDrU74iP6KPcZKv_EVMgHpye_cWD4D-tUn_3NhBAD6OsPSARHSTYAinL2xSeMVKFatnS7scxMrF2UJjLt1BRORqYJwu8KCgTNHuzGLn853dOMdVK_t-QYig9IpLXiTaIGLPn__HrWvU-BMijufDrKb0k0egX3rtiRcs4jmQn6pcrkshwcSGpYREzLAN8XcbWRdkX0lIBuS2smVkXCMIdCd50Eoqa7304yrzw

{
  "beerName": "Beer 5",
  "beerStyle": "ALE",
  "upc": "upc",
  "quantityOnHand": 10,
  "price": 10
}

### DELETE BEER

DELETE http://localhost:8080/api/beer/66bd81b9a797b40fda7be08c
Authorization: Bearer eyJraWQiOiJlM2I0OWYyYy1kYjg4LTQxMzEtOGQyNC03MDhjMmE1MWRlZGYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTcyMzY5NTQ1NCwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJleHAiOjE3MjM2OTU3NTQsImlhdCI6MTcyMzY5NTQ1NCwianRpIjoiMmM2NDhjNDctNzEzZS00MmJhLTg5ZDAtZDY3NzRmYjgzYWZhIn0.UjE2of73f6xN_X59OWDlZym4lL_OH1iKAhYh3mHM4_QOva-RTtaIubm8p_WT6ETIQYtHt5Ll4V1_UK41bmnJnBFRFKMOH_1P8TAYHngjG1SgljXe22cDrU74iP6KPcZKv_EVMgHpye_cWD4D-tUn_3NhBAD6OsPSARHSTYAinL2xSeMVKFatnS7scxMrF2UJjLt1BRORqYJwu8KCgTNHuzGLn853dOMdVK_t-QYig9IpLXiTaIGLPn__HrWvU-BMijufDrKb0k0egX3rtiRcs4jmQn6pcrkshwcSGpYREzLAN8XcbWRdkX0lIBuS2smVkXCMIdCd50Eoqa7304yrzw
