### Get Token from auth server 
POST http://localhost:9000/oauth2/token 
Content-Type: application/x-www-form-urlencoded 
Authorization: Basic messaging-client:secret

grant_type=client_credentials&scope=message.read%20message.write

###

GET http://localhost:8080/api/v2/beer
Authorization: Bearer eyJraWQiOiI5NzMzZmJkYS0xM2RlLTRmOWQtYmIyZi1lYTc1YjQ5YTJlNjYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTcyMzcwMDUzMiwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJleHAiOjE3MjM3MDA4MzIsImlhdCI6MTcyMzcwMDUzMiwianRpIjoiYjhhZTlhMzgtNDhiMi00NmIwLThhOTYtMTA0YjRkMjBjOTY3In0.UWjfVyHUwm8njQoWVk3i3pjy9V0Vww1BmLHG8yshKPwRIv6HhtY0kRqy0CwbJAahsnxBUzM9LDapv_fiu3NFP0cHdZV6mCDRhvQjg7ulDa1hz0Gq_TBgZdgkbRPERPXzCa9IP-1L8c0c-Ub_7I4C5jv0hV8dkpicpyTLR3_CVByPua0P8Wo8rCquo2f-nAh7KAuFwVBeSpdDVHrFAuHW0TNPjRiQjAA1KaWmlXzqSnUwRVPfOpmW0izo-mPoxMpBaNjvY4NTWz62ksrAgqI5Jsl-GkaRq8RfNLNSrl5_vjXYUA0LEU-jC1B-onyC5Edp0u5gw50BRYo0L2XAbIPh2Q
###

GET http://localhost:8080/api/v2/beer/1
Authorization: Bearer eyJraWQiOiIwODNlYTMxMC0zNjRlLTRlOWYtOGJjNy1jNGY2NGYzMjVlNjEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTcyMzcwMDA0Nywic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJleHAiOjE3MjM3MDAzNDcsImlhdCI6MTcyMzcwMDA0NywianRpIjoiNTYzYzA1MjMtYzA5YS00OTkyLWE2NTEtYWVkZTQ5ZWIwMGNiIn0.X4VDqnMy-imrS_bltpGuLxC1NrP2Lmja582zf6F6CZRPH1gbTwuA-sUpOzooETzXBdF1nBkSKX5z6ZGEQTiWwaPKY-UK0qGULaLdyVfZJT6WaCgm5ED0He87O3Ike5wzOjyWHvicTB45CFyApU3lX1g4tKfmqs_R3LRYHVH5MODaANKcqm4smHFgEckbEkTi7dksiObIuuX1lsvQnw9GF6TAHMzB3apAYnPW_1SEUTQ8u7tO0VTI2CQ238v271KbVy6jTgbVIERwphf6MIe0Ekt8ITLrDPbIknbv5At9559WLnQ1O6zZZThRoSMzOVKELadro3Ve48HECvgllsfz8w

###

POST http://localhost:8080/api/v2/beer
Content-Type: application/json
Authorization: Bearer eyJraWQiOiIwODNlYTMxMC0zNjRlLTRlOWYtOGJjNy1jNGY2NGYzMjVlNjEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTcyMzcwMDA0Nywic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJleHAiOjE3MjM3MDAzNDcsImlhdCI6MTcyMzcwMDA0NywianRpIjoiNTYzYzA1MjMtYzA5YS00OTkyLWE2NTEtYWVkZTQ5ZWIwMGNiIn0.X4VDqnMy-imrS_bltpGuLxC1NrP2Lmja582zf6F6CZRPH1gbTwuA-sUpOzooETzXBdF1nBkSKX5z6ZGEQTiWwaPKY-UK0qGULaLdyVfZJT6WaCgm5ED0He87O3Ike5wzOjyWHvicTB45CFyApU3lX1g4tKfmqs_R3LRYHVH5MODaANKcqm4smHFgEckbEkTi7dksiObIuuX1lsvQnw9GF6TAHMzB3apAYnPW_1SEUTQ8u7tO0VTI2CQ238v271KbVy6jTgbVIERwphf6MIe0Ekt8ITLrDPbIknbv5At9559WLnQ1O6zZZThRoSMzOVKELadro3Ve48HECvgllsfz8w

{
    "beerName": "Stella Artois",
    "beerStyle": "PALE_ALE",
    "upc": "upc",
    "quantityOnHand": 12,
    "price": 12
}

###

PUT http://localhost:8080/api/v2/beer/4
Content-Type: application/json
Authorization: eyJraWQiOiIwODNlYTMxMC0zNjRlLTRlOWYtOGJjNy1jNGY2NGYzMjVlNjEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTcyMzcwMDA0Nywic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJleHAiOjE3MjM3MDAzNDcsImlhdCI6MTcyMzcwMDA0NywianRpIjoiNTYzYzA1MjMtYzA5YS00OTkyLWE2NTEtYWVkZTQ5ZWIwMGNiIn0.X4VDqnMy-imrS_bltpGuLxC1NrP2Lmja582zf6F6CZRPH1gbTwuA-sUpOzooETzXBdF1nBkSKX5z6ZGEQTiWwaPKY-UK0qGULaLdyVfZJT6WaCgm5ED0He87O3Ike5wzOjyWHvicTB45CFyApU3lX1g4tKfmqs_R3LRYHVH5MODaANKcqm4smHFgEckbEkTi7dksiObIuuX1lsvQnw9GF6TAHMzB3apAYnPW_1SEUTQ8u7tO0VTI2CQ238v271KbVy6jTgbVIERwphf6MIe0Ekt8ITLrDPbIknbv5At9559WLnQ1O6zZZThRoSMzOVKELadro3Ve48HECvgllsfz8w

{
    "beerName": "Taj Mahal",
    "beerStyle": "PALE_ALE",
    "upc": "upc",
    "quantityOnHand": 12,
    "price": 12
}

###

DELETE http://localhost:8080/api/v2/beer/3
Authorization: Bearer eyJraWQiOiI5NzMzZmJkYS0xM2RlLTRmOWQtYmIyZi1lYTc1YjQ5YTJlNjYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTcyMzcwMDUzMiwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJleHAiOjE3MjM3MDA4MzIsImlhdCI6MTcyMzcwMDUzMiwianRpIjoiYjhhZTlhMzgtNDhiMi00NmIwLThhOTYtMTA0YjRkMjBjOTY3In0.UWjfVyHUwm8njQoWVk3i3pjy9V0Vww1BmLHG8yshKPwRIv6HhtY0kRqy0CwbJAahsnxBUzM9LDapv_fiu3NFP0cHdZV6mCDRhvQjg7ulDa1hz0Gq_TBgZdgkbRPERPXzCa9IP-1L8c0c-Ub_7I4C5jv0hV8dkpicpyTLR3_CVByPua0P8Wo8rCquo2f-nAh7KAuFwVBeSpdDVHrFAuHW0TNPjRiQjAA1KaWmlXzqSnUwRVPfOpmW0izo-mPoxMpBaNjvY4NTWz62ksrAgqI5Jsl-GkaRq8RfNLNSrl5_vjXYUA0LEU-jC1B-onyC5Edp0u5gw50BRYo0L2XAbIPh2Q
