###

GET http://localhost:8080/api/v2/beer

###

GET http://localhost:8080/api/v2/beer/1

###

POST http://localhost:8080/api/v2/beer
Content-Type: application/json

{
    "beerName": "Stella Artois",
    "beerStyle": "PALE_ALE",
    "upc": "upc",
    "quantityOnHand": 12,
    "price": 12
}